<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'App\\www\\Controllers\\__class' => $baseDir . '/App/www/Controllers/__class.php',
    'Fix\\Exception\\Error' => $baseDir . '/Fix/Exception/Error.php',
    'Fix\\Internal\\Assets\\Pages' => $baseDir . '/Fix/Internal/Assets/Pages.php',
    'Fix\\Internal\\Database\\Pdo' => $baseDir . '/Fix/Internal/Database/Pdo.php',
    'Fix\\Internal\\Model\\Model' => $baseDir . '/Fix/Internal/Model/Model.php',
    'Fix\\Kernel\\Filter' => $baseDir . '/Fix/Kernel/Filter.php',
    'Fix\\Kernel\\Kernel' => $baseDir . '/Fix/Kernel/Kernel.php',
    'Fix\\Kernel\\Url' => $baseDir . '/Fix/Kernel/Url.php',
    'Fix\\Middleware\\Middleware' => $baseDir . '/Fix/Middleware/Middleware.php',
    'Fix\\Mode\\Request' => $baseDir . '/Fix/Mode/Request.php',
    'Fix\\Router\\Router' => $baseDir . '/Fix/Router/Router.php',
    'Fix\\Settings\\App' => $baseDir . '/Fix/Settings/App.php',
    'Fix\\Settings\\Kernel' => $baseDir . '/Fix/Settings/Kernel.php',
    'Fix\\Support\\Header' => $baseDir . '/Fix/Support/Header.php',
    'Fix\\Support\\Json' => $baseDir . '/Fix/Support/Json.php',
    'Fix\\Support\\Support' => $baseDir . '/Fix/Support/Support.php',
    'Fix\\Support\\Translate' => $baseDir . '/Fix/Support/Translate.php',
);
